# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_auto_20171222_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=None, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paylaneauthorization',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.PaylaneTransaction'),
        ),
    ]
