# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 15:59
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import django_fsm
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('billing', '0002_auto_20171120_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('amount_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'EUR €'), ('USD', 'USD $')], default='EUR', editable=False, max_length=3)),
                ('amount', djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='EUR', max_digits=10)),
                ('state', django_fsm.FSMField(choices=[('New', 'Nuevo'), ('Completed', 'Completed'), ('No Valid', 'No Valid'), ('Canceled', 'Canceled'), ('Returned', 'Returned')], db_index=True, default='New', max_length=50, protected=True, verbose_name='Order State')),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_order', to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Orders',
                'ordering': ('id',),
            },
        ),
    ]
