# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 09:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('payment_status', models.CharField(choices=[('New', 'Nuevo'), ('Completed', 'Completed'), ('No Valid', 'No Valid'), ('Canceled', 'Canceled'), ('Returned', 'Returned'), ('Error', 'Error')], db_index=True, default='New', max_length=200)),
                ('payment_message', models.CharField(blank=True, max_length=200, null=True)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=django_fsm.FSMField(choices=[('New', 'Nuevo'), ('Completed', 'Completed'), ('No Valid', 'No Valid'), ('Canceled', 'Canceled'), ('Returned', 'Returned'), ('Error', 'Error')], db_index=True, default='New', max_length=50, protected=True, verbose_name='Order State'),
        ),
    ]
